#!/usr/bin/env sh

# 检查 husky.sh 是否存在
if [ -f "$(dirname -- "$0")/_/husky.sh" ]; then
  . "$(dirname -- "$0")/_/husky.sh"
else
  echo "husky.sh not found!"
  exit 1
fi

# 调用 npx 命令
npx --commitlint --edit "${1}"
